name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the main repository and submodules
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true  # Initialize and update submodules automatically

    # Step 2: (Optional) Install dependencies, build, etc.
    # Add your existing build or test steps here
    # - name: Install dependencies
    #   run: npm install

    # Step 3: Pull and update submodule to the latest commit
    - name: Pull and update submodule
      run: |
        git submodule update --remote --recursive
        git add .

    # Step 4: Commit the updated submodule reference
    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git commit -m "Auto-update submodule to the latest commit" || echo "No changes to commit"

    # Step 5: Push changes back to the main repository
    - name: Push changes
      run: |
        git push origin main || echo "No changes to push"
